model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4                          # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: text-completion-openai/gpt-4 # The `text-completion-openai/` prefix will call openai.completions.create
      api_key: os.environ/OPENAI_API_KEY